- name: Install packages
  apt:
    pkg: "{{ item }}"
    update_cache: true
  with_items:
    - openvpn
    - easy-rsa

- name: Create configuration from configuration
  template:
    src: "server.conf.j2"
    dest: "/etc/openvpn/server.conf"
    owner: root
    mode: 0644

- name: Implementing forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Copying easy-rsa
  copy:
    src: "/usr/share/easy-rsa"
    dest: "/etc/openvpn/"
#    recurse: yes
    mode: 0744
    remote_src: false
  tags:
   - test

- name: Create vars directory
  file:
    path: /etc/openvpn/easy-rsa/keys
    state: directory
