- name: Install packages
  apt:
    pkg: "{{ item }}"
    update_cache: true
  with_items:
    - openvpn
    - easy-rsa

- name: Create configuration from configuration
  template:
    src: "server.conf.j2"
    dest: "/etc/openvpn/server.conf"
    owner: root
    mode: 0644
